#!/bin/sh

if [[ -d gpiopins ]]; then
	rm -r gpiopins
fi
mkdir gpiopins
cd gpiopins
for dir in $(ls -d /sys/class/gpio/gpiochip*); do
	chipLabel=$(cat $dir/label)
	if [[ $chipLabel == mcp230* ]]; then
		base=$(cat $dir/base)
		ngpio=$(cat $dir/ngpio)
		i2cDev=$(cd $dir/device/driver/;ls -d *-*)
		mkdir $i2cDev
		cd $i2cDev
		for ((i=0;i<ngpio;i++)); do
			portName=$(echo -e "GP\x$((41+i/8))$((i%8))")
			gpioNumber=$((base+i))
			if [[ -e /sys/class/gpio/gpio$gpioNumber ]]; then
				echo $gpioNumber > /sys/class/gpio/unexport
			fi
			echo $gpioNumber > /sys/class/gpio/export
			ln -s /sys/class/gpio/gpio$gpioNumber $portName
			echo "$i2cDev : Added $portName->gpio$gpioNumber"
		done
	fi
done
